### PR TITLE
Bring in 3 commits from PyEVTK BitBucket repo and 1 from paulo-herrera/PyEVTK on github

### PR DESCRIPTION
**Pull request by xylar**
As best I can see, these are the relevant commits from these two repos that haven't been mirrored here.  The original commits are:
https://bitbucket.org/pauloh/pyevtk/commits/c3c076129dbc6a3bebc801c8929baf9f1d1c74ca
https://bitbucket.org/pauloh/pyevtk/commits/4e759fe42afa605415cbe2e5127112efa7571213 https://bitbucket.org/pauloh/pyevtk/commits/5d22e9cd10a0f67ae4ab3fa6c8cdcc41c7d694a3
https://github.com/paulo-herrera/PyEVTK/commit/823d84a6fc0fcd684a1f5d2355f86c14ed4653b0

### CODE REVIEW

**Comment by xylar** [comment]
This PR is based off of #11, so it shouldn't be merged until after that one.

**Comment by xylar** [comment]
Wow, I'm really impressed with the CI you've set up!

**Comment by somada141** [comment]
> Wow, I'm really impressed with the CI you've set up!

That was all @renefritze. He's done a great job :)

**Comment by somada141** [comment]
I'll review as soon as I get a chance

**Comment by xylar** [comment]
Thanks @renefritze!

**Pull request merged**
