### PR TITLE
added keyword for name of dataset in a collection

### LINKED ISSUE #30: Name for Blocks (Datasets) in Collection (Multi-Block Dataset)
I was able to use the `pointsToVTK` and `VtkGroup` functions to generate a Multiblock-Data Collection. However, for larger Collection it becomes difficult to know which Block inside the Collecton corresponds to which Data.

After doing a bit of Internet-search and also trying for myself, I was able to find out how I can "name" the Blocks (i.E. Datasets) inside a Collection, just by adding the "name" attribute (in this case by hand):

```xml
<?xml version="1.0"?>
<VTKFile type="Collection" version="0.1" byte_order="LittleEndian">
<Collection>
<DataSet timestep="0" group="" part="0" name="2.50mm" file="vtk/SSB_JetABC__XZ_Plane_x_loc=_2.50_mm.vtu"/>
<DataSet timestep="0" group="" part="0" name="" file="vtk/SSB_JetABC__XZ_Plane_x_loc=_15.00_mm.vtu"/>
<DataSet timestep="0" group="" part="0" file="vtk/SSB_JetABC__XZ_Plane_x_loc=_30.00_mm.vtu"/>
</Collection>
</VTKFile>
```

Resulting in the following Data Hierarchy:
grafik

As you can see, that for the first Dataset, the MultiBlock is named "2.50mm", as specified, and the other two are still name "Multi-block Dataset", regardless whether the value for name was blank or not given.

I already tried to insert it into the code, maybe you can then test it and hopefully merge it into a new tag. The changes would be the following:
https://github.com/pyscience-projects/pyevtk/blob/5cb3370a2ef1b6549ab5bde2d39df0e19f7ffabc/pyevtk/vtk.py#L211

```python
    def addFile(self, filepath, sim_time, group="", part="0", name=""):
```

https://github.com/pyscience-projects/pyevtk/blob/5cb3370a2ef1b6549ab5bde2d39df0e19f7ffabc/pyevtk/vtk.py#L236-L238
```python
        self.xml.addAttributes(
            timestep=sim_time, group=group, part=part, file=filename, name=name
        )
```

### PR DESCRIPTION
**Pull request by StRuoff**
Fix #30

### CODE REVIEW

**Review by renefritze — APPROVED** [review]

**Comment by renefritze** [comment]
Looks good. I see no reason not to merge this. Thank you for your contribution! Releasing `v1.3` right away.

**Comment by StRuoff** [comment]
> Edit: `v1.4.0` actually

(When) Will the package be available for conda? In the PyPI repo I can already see it.

**Comment by renefritze** [comment]
It may take a couple of hours to a day or so until the conda-forge bot updates the feedstock via PR. You can watch [this repo](https://github.com/conda-forge/pyevtk-feedstock/pulls) for updates.

**Comment by StRuoff** [comment]
I just checked the new versions from PyPI and conda, but they both seem to lack the new parts of the code. Did something go wrong there?
If i download the zip/tar file for the [tag](https://github.com/pyscience-projects/pyevtk/releases/tag/v1.4.0), the changes are not in them.

**Comment by renefritze** [comment]
> I just checked the new versions from PyPI and conda, but they both seem to lack the new parts of the code. Did something go wrong there?
> If i download the zip/tar file for the [tag](https://github.com/pyscience-projects/pyevtk/releases/tag/v1.4.0), the changes are not in them.

My fault. Tagged the wrong commit. Sorry for that. Machinery is running for `v1.4.1` now

**Pull request merged**
