### PR TITLE
Fix attributes (#27)

### LINKED ISSUE #27: Dataset attributes bug
I noticed two bugs with the dataset attributes:
- The dataset attributes are written lowercase, which seems wrong. The output results in `<CellData scalars="test">`, while `<CellData Scalars="test">` would be correct. For definition of the VTK names see here: https://gitlab.kitware.com/vtk/vtk/-/blob/v9.0.1/Common/DataModel/vtkDataSetAttributes.cxx#L42
I do not know how VTK and ParaView (should) handle this internally. I found a few code points where it looks like they at least sometimes do a case insensitive check, but ParaView only works fully as expected when using the uppercase first letter `Scalars`. Also files exported by ParaView use the uppercase first letter.
Bug probably is here: https://github.com/pyscience-projects/pyevtk/blob/v1.2.0/pyevtk/vtk.py#L389-L398
- The second bug is in the high-level interface: https://github.com/pyscience-projects/pyevtk/blob/v1.2.0/pyevtk/hl.py#L48-L57
There, always the first key is set as scalar array, no matter if the data behind this key is scalar or vector data. Also the `Vectors` attribute is never set at all, even if there is vector data.

### PR DESCRIPTION
**Pull request by moritz-h**
Fix #27.
- Fix attributes typo
- Set a valid scalar/vector data key as attribute. Just use the first matching key from the list. The check if data is scalar or vector is the same as used in `addData()`

### CODE REVIEW

**Comment by renefritze** [comment]
Thank you for the PR @moritz-h! Could you change the `type().__name__` checks to use `isinstance` instead? Otherwise I think this can be merged directly and also warrants a new release.

**Comment by moritz-h** [comment]
@renefritze I copied the check from within vtkFile.addData(), which is called directly after: https://github.com/pyscience-projects/pyevtk/blob/v1.2.0/pyevtk/vtk.py#L533
I think it would make sense to keep this consistent. Do you prefer to update update both places then or should I avoid changes within vtk.py?

**Comment by renefritze** [comment]
> @renefritze I copied the check from within vtkFile.addData(), which is called directly after: https://github.com/pyscience-projects/pyevtk/blob/v1.2.0/pyevtk/vtk.py#L533

> I think it would make sense to keep this consistent. 
Agreed.
> Do you prefer to update update both places then or should I avoid changes within vtk.py?
I would prefer updating both places, if you don't mind. Maybe the `ndarray` check too?

**Comment by moritz-h** [comment]
@renefritze Should be done

**Review by renefritze — APPROVED** [review]
Excellent, thank you.

**Comment by renefritze** [comment]
I'll have to look into the apparently broken GH action before I do the next release, and it might be a few days before I get to that.

**Comment by moritz-h** [comment]
It looks like an authentication issue to pypi. I think the reason might be that third party pull request do not have access to the secret defined in the GitHub workflow. (Which is generally a very good idea from security perspective.)

**Comment by renefritze** [comment]
> It looks like an authentication issue to pypi. I think the reason might be that third party pull request do not have access to the secret defined in the GitHub workflow. (Which is generally a very good idea from security perspective.)

Yeah, my issue is only that I remembered having that setup so it at least wouldn't fail the PR check.

**Comment by moritz-h** [comment]
I think this line may is wrong: https://github.com/pyscience-projects/pyevtk/blob/master/.github/workflows/test_deploy.yml#L6
The deploy test may only should run when it is merged into master and not onto pull requests.

While wanting to use a static URL above, I noticed, when switching back to v1.2.0, there this line is exactly like what my idea would have been: https://github.com/pyscience-projects/pyevtk/blob/v1.2.0/.github/workflows/test_deploy.yml

Maybe this change to test_deploy.yml within this commit was unintentional and it has worked before: https://github.com/pyscience-projects/pyevtk/commit/571426c4272a93c756b6aae0b8b27bed5cbde160#diff-6b5ff66c8969e24f75b0e7d96ffd86e0939f2e7ef4ed90658d6c054fafcee1fa

**Comment by renefritze** [comment]
You are absolutely right, that is an entirely unrelated and weird change in  571426c. Good catch! Thanks!

**Comment by renefritze** [comment]
1.3.0 is now out with your fixes included @moritz-h. Thanks again!

**Pull request merged**
